-- +goose Up
insert into "companies" (name) values ('Каспийский трубопроводный консорциум');
insert into "companies" (name) values ('Агентство по страхованию вкладов');
insert into "companies" (name) values ('Торговая компания Мегаполис');
insert into "companies" (name) values ('Российские железные дороги');
insert into "companies" (name) values ('Автопремиум / Платформа А');
insert into "companies" (name) values ('Первая грузовая компания');
insert into "companies" (name) values ('Издательство Просвещение');
insert into "companies" (name) values ('Фонд развития территорий');
insert into "companies" (name) values ('Универсальная логистика');
insert into "companies" (name) values ('ФРЕКО (RECO-Гарантия)');
insert into "companies" (name) values ('Банк Санкт-Петербург');
insert into "companies" (name) values ('НКО Мобильная карта');
insert into "companies" (name) values ('Синарастройкомплект');
insert into "companies" (name) values ('Норильский никель');
insert into "companies" (name) values ('PBB (Wildberries)');
insert into "companies" (name) values ('ГК Нацпроектстрой');
insert into "companies" (name) values ('Стройпроектсервис');
insert into "companies" (name) values ('Сыктывкарский ЛПК');
insert into "companies" (name) values ('Московская биржа');
insert into "companies" (name) values ('АльфаСтрахование');
insert into "companies" (name) values ('Трансмашхолдинг');
insert into "companies" (name) values ('Сургутнефтегаз');
insert into "companies" (name) values ('Атомэнергопром');
insert into "companies" (name) values ('Россельхозбанк');
insert into "companies" (name) values ('Вкусно и точка');
insert into "companies" (name) values ('Золотая корона');
insert into "companies" (name) values ('СИБУР Холдинг');
insert into "companies" (name) values ('Металлоинвест');
insert into "companies" (name) values ('Промсвязьбанк');
insert into "companies" (name) values ('СК Русьветпро');
insert into "companies" (name) values ('Усть-Луга Ойл');
insert into "companies" (name) values ('Томинский ГОК');
insert into "companies" (name) values ('Чарли и падар');
insert into "companies" (name) values ('Т-Технологии');
insert into "companies" (name) values ('Зарубежнефть');
insert into "companies" (name) values ('Мосводоканал');
insert into "companies" (name) values ('Газпромбанк');
insert into "companies" (name) values ('МХК Еврохим');
insert into "companies" (name) values ('Детский мир');
insert into "companies" (name) values ('Вектор Рейл');
insert into "companies" (name) values ('Globaltrans');
insert into "companies" (name) values ('НПФ Газфонд');
insert into "companies" (name) values ('Новикомбанк');
insert into "companies" (name) values ('Модум-Транс');
insert into "companies" (name) values ('ТК МС-Трейд');
insert into "companies" (name) values ('ГК Динамика');
insert into "companies" (name) values ('Технониколь');
insert into "companies" (name) values ('Удмуртнефть');
insert into "companies" (name) values ('Транснефть');
insert into "companies" (name) values ('Альфа-банк');
insert into "companies" (name) values ('Северсталь');
insert into "companies" (name) values ('Совкомбанк');
insert into "companies" (name) values ('Гранд Сити');
insert into "companies" (name) values ('Совкомфлот');
insert into "companies" (name) values ('Ингосстрах');
insert into "companies" (name) values ('ДНС Ритейл');
insert into "companies" (name) values ('Полиметалл');
insert into "companies" (name) values ('Группа ЛСР');
insert into "companies" (name) values ('Трансфин-М');
insert into "companies" (name) values ('Ростелеком');
insert into "companies" (name) values ('HeadHunter');
insert into "companies" (name) values ('Велесстрой');
insert into "companies" (name) values ('Интер РАО');
insert into "companies" (name) values ('Уралкалий');
insert into "companies" (name) values ('Fix Price');
insert into "companies" (name) values ('Роснефть');
insert into "companies" (name) values ('Татнефть');
insert into "companies" (name) values ('X5 Group');
insert into "companies" (name) values ('Аэрофлот');
insert into "companies" (name) values ('Руснефть');
insert into "companies" (name) values ('Мираторг');
insert into "companies" (name) values ('Газпром');
insert into "companies" (name) values ('Новатэк');
insert into "companies" (name) values ('Фосагро');
insert into "companies" (name) values ('МегаФон');
insert into "companies" (name) values ('НПК ОВК');
insert into "companies" (name) values ('РусАгро');
insert into "companies" (name) values ('Winline');
insert into "companies" (name) values ('Лукойл');
insert into "companies" (name) values ('ВЭБ.РФ');
insert into "companies" (name) values ('Дом.РФ');
insert into "companies" (name) values ('МАГНИТ');
insert into "companies" (name) values ('ФОНБЕТ');
insert into "companies" (name) values ('Полюс');
insert into "companies" (name) values ('Акрон');
insert into "companies" (name) values ('FESCO');
insert into "companies" (name) values ('Лента');
insert into "companies" (name) values ('Сбер');
insert into "companies" (name) values ('НЛМК');
insert into "companies" (name) values ('РНПК');
insert into "companies" (name) values ('A101');
insert into "companies" (name) values ('Озон');
insert into "companies" (name) values ('ВТБ');
insert into "companies" (name) values ('Эн+');
insert into "companies" (name) values ('ММК');
insert into "companies" (name) values ('ИНК');
insert into "companies" (name) values ('МТС');
insert into "companies" (name) values ('ПИК');
insert into "companies" (name) values ('Т1');

-- +goose Down
truncate table "companies";
