apiVersion: batch/v1
kind: Job
metadata:
  name: cu-faculty-migrate
  namespace: dev
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: cu-faculty-migrate
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: migrate
          image: IMAGE_PLACEHOLDER
          args: ["migrate"]
          envFrom:
            - secretRef:
                name: cu-faculty-backend-env
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
