-- +goose Up
insert into "key_skills" (name) values ('Событийно-ориентированная архитектура');
insert into "key_skills" (name) values ('Обработка естественного языка');
insert into "key_skills" (name) values ('Микросервисная архитектура');
insert into "key_skills" (name) values ('Пользовательские интервью');
insert into "key_skills" (name) values ('Реагирование на инциденты');
insert into "key_skills" (name) values ('Техническая документация');
insert into "key_skills" (name) values ('Паттерны проектирования');
insert into "key_skills" (name) values ('Статистический анализ');
insert into "key_skills" (name) values ('Продуктовая аналитика');
insert into "key_skills" (name) values ('Планирование roadmap');
insert into "key_skills" (name) values ('Customer Development');
insert into "key_skills" (name) values ('Компьютерное зрение');
insert into "key_skills" (name) values ('Моделирование угроз');
insert into "key_skills" (name) values ('Адаптивная верстка');
insert into "key_skills" (name) values ('Power BI');
insert into "key_skills" (name) values ('Управление backlog');
insert into "key_skills" (name) values ('Оценка уязвимостей');
insert into "key_skills" (name) values ('Адаптивный дизайн');
insert into "key_skills" (name) values ('Машинное обучение');
insert into "key_skills" (name) values ('Глубокое обучение');
insert into "key_skills" (name) values ('Swagger / OpenAPI');
insert into "key_skills" (name) values ('Анализ требований');
insert into "key_skills" (name) values ('Entity Framework');
insert into "key_skills" (name) values ('A/B тестирование');
insert into "key_skills" (name) values ('Документация API');
insert into "key_skills" (name) values ('Прототипирование');
insert into "key_skills" (name) values ('Jetpack Compose');
insert into "key_skills" (name) values ('GitHub Actions');
insert into "key_skills" (name) values ('Ruby on Rails');
insert into "key_skills" (name) values ('Apollo Client');
insert into "key_skills" (name) values ('ASP.NET Core');
insert into "key_skills" (name) values ('React Native');
insert into "key_skills" (name) values ('scikit-learn');
insert into "key_skills" (name) values ('transformers');
insert into "key_skills" (name) values ('REST Assured');
insert into "key_skills" (name) values ('ER-диаграммы');
insert into "key_skills" (name) values ('User Stories');
insert into "key_skills" (name) values ('Криптография');
insert into "key_skills" (name) values ('Objective-C');
insert into "key_skills" (name) values ('Spring Boot');
insert into "key_skills" (name) values ('JavaScript');
insert into "key_skills" (name) values ('TypeScript');
insert into "key_skills" (name) values ('Coroutines');
insert into "key_skills" (name) values ('TensorFlow');
insert into "key_skills" (name) values ('PostgreSQL');
insert into "key_skills" (name) values ('SQL Server');
insert into "key_skills" (name) values ('ClickHouse');
insert into "key_skills" (name) values ('Delta Lake');
insert into "key_skills" (name) values ('Kubernetes');
insert into "key_skills" (name) values ('Prometheus');
insert into "key_skills" (name) values ('Playwright');
insert into "key_skills" (name) values ('Пентестинг');
insert into "key_skills" (name) values ('Burp Suite');
insert into "key_skills" (name) values ('Confluence');
insert into "key_skills" (name) values ('Hibernate');
insert into "key_skills" (name) values ('Cassandra');
insert into "key_skills" (name) values ('Snowflake');
insert into "key_skills" (name) values ('Terraform');
insert into "key_skills" (name) values ('GitLab CI');
insert into "key_skills" (name) values ('ELK Stack');
insert into "key_skills" (name) values ('Use Cases');
insert into "key_skills" (name) values ('Код-ревью');
insert into "key_skills" (name) values ('LightGBM');
insert into "key_skills" (name) values ('BigQuery');
insert into "key_skills" (name) values ('Redshift');
insert into "key_skills" (name) values ('RabbitMQ');
insert into "key_skills" (name) values ('Debezium');
insert into "key_skills" (name) values ('Selenium');
insert into "key_skills" (name) values ('Espresso');
insert into "key_skills" (name) values ('Metabase');
insert into "key_skills" (name) values ('REST API');
insert into "key_skills" (name) values ('Firewall');
insert into "key_skills" (name) values ('Adobe XD');
insert into "key_skills" (name) values ('FastAPI');
insert into "key_skills" (name) values ('Node.js');
insert into "key_skills" (name) values ('Express');
insert into "key_skills" (name) values ('Laravel');
insert into "key_skills" (name) values ('Symfony');
insert into "key_skills" (name) values ('Next.js');
insert into "key_skills" (name) values ('Nuxt.js');
insert into "key_skills" (name) values ('Angular');
insert into "key_skills" (name) values ('Zustand');
insert into "key_skills" (name) values ('SwiftUI');
insert into "key_skills" (name) values ('Flutter');
insert into "key_skills" (name) values ('PyTorch');
insert into "key_skills" (name) values ('XGBoost');
insert into "key_skills" (name) values ('MongoDB');
insert into "key_skills" (name) values ('Ansible');
insert into "key_skills" (name) values ('Jenkins');
insert into "key_skills" (name) values ('Grafana');
insert into "key_skills" (name) values ('HAProxy');
insert into "key_skills" (name) values ('Webpack');
insert into "key_skills" (name) values ('PHPUnit');
insert into "key_skills" (name) values ('Cypress');
insert into "key_skills" (name) values ('Postman');
insert into "key_skills" (name) values ('Gatling');
insert into "key_skills" (name) values ('Tableau');
insert into "key_skills" (name) values ('Airflow');
insert into "key_skills" (name) values ('Prefect');
insert into "key_skills" (name) values ('GraphQL');
insert into "key_skills" (name) values ('IDS/IPS');
insert into "key_skills" (name) values ('PCI DSS');
insert into "key_skills" (name) values ('Kotlin');
insert into "key_skills" (name) values ('Groovy');
insert into "key_skills" (name) values ('Python');
insert into "key_skills" (name) values ('MATLAB');
insert into "key_skills" (name) values ('Django');
insert into "key_skills" (name) values ('NestJS');
insert into "key_skills" (name) values ('pandas');
insert into "key_skills" (name) values ('OpenCV');
insert into "key_skills" (name) values ('Oracle');
insert into "key_skills" (name) values ('Pulsar');
insert into "key_skills" (name) values ('Hadoop');
insert into "key_skills" (name) values ('Docker');
insert into "key_skills" (name) values ('Puppet');
insert into "key_skills" (name) values ('ArgoCD');
insert into "key_skills" (name) values ('Zabbix');
insert into "key_skills" (name) values ('TCP/IP');
insert into "key_skills" (name) values ('pytest');
insert into "key_skills" (name) values ('Appium');
insert into "key_skills" (name) values ('XCTest');
insert into "key_skills" (name) values ('JMeter');
insert into "key_skills" (name) values ('Splunk');
insert into "key_skills" (name) values ('QRadar');
insert into "key_skills" (name) values ('Notion');
insert into "key_skills" (name) values ('Scala');
insert into "key_skills" (name) values ('Swift');
insert into "key_skills" (name) values ('Julia');
insert into "key_skills" (name) values ('Maven');
insert into "key_skills" (name) values ('Flask');
insert into "key_skills" (name) values ('React');
insert into "key_skills" (name) values ('Redux');
insert into "key_skills" (name) values ('Relay');
insert into "key_skills" (name) values ('UIKit');
insert into "key_skills" (name) values ('NumPy');
insert into "key_skills" (name) values ('spaCy');
insert into "key_skills" (name) values ('MySQL');
insert into "key_skills" (name) values ('Redis');
insert into "key_skills" (name) values ('Kafka');
insert into "key_skills" (name) values ('Spark');
insert into "key_skills" (name) values ('Linux');
insert into "key_skills" (name) values ('Nginx');
insert into "key_skills" (name) values ('Azure');
insert into "key_skills" (name) values ('JUnit');
insert into "key_skills" (name) values ('OWASP');
insert into "key_skills" (name) values ('Figma');
insert into "key_skills" (name) values ('Java');
insert into "key_skills" (name) values ('Rust');
insert into "key_skills" (name) values ('Ruby');
insert into "key_skills" (name) values ('Dart');
insert into "key_skills" (name) values ('Bash');
insert into "key_skills" (name) values ('.NET');
insert into "key_skills" (name) values ('Echo');
insert into "key_skills" (name) values ('Ktor');
insert into "key_skills" (name) values ('Vuex');
insert into "key_skills" (name) values ('RxJS');
insert into "key_skills" (name) values ('MobX');
insert into "key_skills" (name) values ('NLTK');
insert into "key_skills" (name) values ('Hive');
insert into "key_skills" (name) values ('Helm');
insert into "key_skills" (name) values ('Flux');
insert into "key_skills" (name) values ('Loki');
insert into "key_skills" (name) values ('HTTP');
insert into "key_skills" (name) values ('HTML');
insert into "key_skills" (name) values ('Sass');
insert into "key_skills" (name) values ('Less');
insert into "key_skills" (name) values ('Vite');
insert into "key_skills" (name) values ('Jest');
insert into "key_skills" (name) values ('gRPC');
insert into "key_skills" (name) values ('BPMN');
insert into "key_skills" (name) values ('GDPR');
insert into "key_skills" (name) values ('Jira');
insert into "key_skills" (name) values ('Miro');
insert into "key_skills" (name) values ('C++');
insert into "key_skills" (name) values ('PHP');
insert into "key_skills" (name) values ('SQL');
insert into "key_skills" (name) values ('Gin');
insert into "key_skills" (name) values ('Vue');
insert into "key_skills" (name) values ('DNS');
insert into "key_skills" (name) values ('AWS');
insert into "key_skills" (name) values ('GCP');
insert into "key_skills" (name) values ('IAM');
insert into "key_skills" (name) values ('VPC');
insert into "key_skills" (name) values ('WAF');
insert into "key_skills" (name) values ('CSS');
insert into "key_skills" (name) values ('PWA');
insert into "key_skills" (name) values ('OKR');
insert into "key_skills" (name) values ('KPI');
insert into "key_skills" (name) values ('UML');
insert into "key_skills" (name) values ('PKI');
insert into "key_skills" (name) values ('Git');
insert into "key_skills" (name) values ('C#');
insert into "key_skills" (name) values ('Go');
insert into "key_skills" (name) values ('S3');
insert into "key_skills" (name) values ('C');
insert into "key_skills" (name) values ('R');

insert into "soft_skills" (name) values ('Кроссфункциональное взаимодействие');
insert into "soft_skills" (name) values ('Проблемноориентированное мышление');
insert into "soft_skills" (name) values ('Асинхронная коммуникация');
insert into "soft_skills" (name) values ('Письменная коммуникация');
insert into "soft_skills" (name) values ('Презентационные навыки');
insert into "soft_skills" (name) values ('Управление конфликтами');
insert into "soft_skills" (name) values ('Аналитическое мышление');
insert into "soft_skills" (name) values ('Публичные выступления');
insert into "soft_skills" (name) values ('Управление ожиданиями');
insert into "soft_skills" (name) values ('Критическое мышление');
insert into "soft_skills" (name) values ('Ведение переговоров');
insert into "soft_skills" (name) values ('Стрессоустойчивость');
insert into "soft_skills" (name) values ('Коммуникабельность');
insert into "soft_skills" (name) values ('Декомпозиция задач');
insert into "soft_skills" (name) values ('Системное мышление');
insert into "soft_skills" (name) values ('Работа в команде');
insert into "soft_skills" (name) values ('Удаленная работа');
insert into "soft_skills" (name) values ('Документирование');
insert into "soft_skills" (name) values ('Тайм-менеджмент');
insert into "soft_skills" (name) values ('Самоорганизация');
insert into "soft_skills" (name) values ('Ответственность');
insert into "soft_skills" (name) values ('Английский язык');
insert into "soft_skills" (name) values ('Обратная связь');
insert into "soft_skills" (name) values ('Инициативность');
insert into "soft_skills" (name) values ('Адаптивность');
insert into "soft_skills" (name) values ('Креативность');
insert into "soft_skills" (name) values ('Обучаемость');
insert into "soft_skills" (name) values ('Менторство');
insert into "soft_skills" (name) values ('Лидерство');


-- +goose Down
truncate table "soft_skills";
truncate table "key_skills";
