-- +goose Up
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ НЕФТИ И ГАЗА (НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ) ИМЕНИ И.М. ГУБКИНА', 'ГУБКИНСКИЙ УНИВЕРСИТЕТ');
insert into "universities" (name, short_name) values ('МОСКОВСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ Н.Э. БАУМАНА (НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ)', 'МГТУ ИМ. Н.Э. БАУМАНА');
insert into "universities" (name, short_name) values ('САРАТОВСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ГЕНЕТИКИ, БИОТЕХНОЛОГИИ И ИНЖЕНЕРИИ ИМЕНИ Н.И. ВАВИЛОВА', 'ВАВИЛОВСКИЙ УНИВЕРСИТЕТ');
insert into "universities" (name, short_name) values ('САНКТ-ПЕТЕРБУРГСКАЯ ГОСУДАРСТВЕННАЯ ХУДОЖЕСТВЕННО-ПРОМЫШЛЕННАЯ АКАДЕМИЯ ИМЕНИ А.Л. ШТИГЛИЦА', 'СПГХПА ИМ. А.Л. ШТИГЛИЦА');
insert into "universities" (name, short_name) values ('САНКТ-ПЕТЕРБУРГСКИЙ ГОСУДАРСТВЕННЫЙ ЭЛЕКТРОТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ "ЛЭТИ" ИМ. В.И. УЛЬЯНОВА (ЛЕНИНА)', 'СПБГЭТУ "ЛЭТИ');
insert into "universities" (name, short_name) values ('СИБИРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ НАУКИ И ТЕХНОЛОГИЙ ИМЕНИ АКАДЕМИКА М.Ф. РЕШЕТНЕВА', 'СИБГУ ИМ. М.Ф. РЕШЕТНЕВА');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ ГОСУДАРСТВЕННЫЙ ХУДОЖЕСТВЕННО-ПРОМЫШЛЕННЫЙ УНИВЕРСИТЕТ ИМ. С.Г. СТРОГАНОВА', 'РГХПУ ИМ. С. Г. СТРОГАНОВА');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМ. А.Н. КОСЫГИНА (ТЕХНОЛОГИИ. ДИЗАЙН. ИСКУССТВО)', 'РГУ ИМ. А.Н. КОСЫГИНА');
insert into "universities" (name, short_name) values ('РЫБИНСКИЙ ГОСУДАРСТВЕННЫЙ АВИАЦИОННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ П.А. СОЛОВЬЕВА', 'РГАТУ ИМЕНИ П.А. СОЛОВЬЕВА');
insert into "universities" (name, short_name) values ('ВЛАДИМИРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ АЛЕКСАНДРА ГРИГОРЬЕВИЧА И НИКОЛАЯ ГРИГОРЬЕВИЧА СТОЛЕТОВЫХ', 'ВЛГУ');
insert into "universities" (name, short_name) values ('ПЕРМСКИЙ ГОСУДАРСТВЕННЫЙ АГРАРНО-ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ АКАДЕМИКА Д.Н. ПРЯНИШНИКОВА', 'ПЕРМСКИЙ ГАТУ');
insert into "universities" (name, short_name) values ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ МОРДОВСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМ. Н.П. ОГАРЁВА', 'МГУ ИМ. Н.П. ОГАРЁВА');
insert into "universities" (name, short_name) values ('СЕВЕРО-КАВКАЗСКИЙ ГОРНО-МЕТАЛЛУРГИЧЕСКИЙ ИНСТИТУТ (ГОСУДАРСТВЕННЫЙ ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ)', 'СКГМИ (ГТУ)');
insert into "universities" (name, short_name) values ('САМАРСКИЙ НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ ИМЕНИ АКАДЕМИКА С.П.КОРОЛЕВА', 'САМАРСКИЙ УНИВЕРСИТЕТ');
insert into "universities" (name, short_name) values ('ИЖЕВСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ М.Т. КАЛАШНИКОВА', 'ИЖГТУ ИМЕНИ М.Т. КАЛАШНИКОВА');
insert into "universities" (name, short_name) values ('НОВОСИБИРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ АРХИТЕКТУРЫ, ДИЗАЙНА И ИСКУССТВ ИМЕНИ А.Д. КРЯЧКОВА', 'НГУАДИ');
insert into "universities" (name, short_name) values ('КОВРОВСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ В.А. ДЕГТЯРЕВА', 'КГТУ ИМ. В.А. ДЕГТЯРЕВА');
insert into "universities" (name, short_name) values ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ НИЖЕГОРОДСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМ. Н.И. ЛОБАЧЕВСКОГО', 'ННГУ');
insert into "universities" (name, short_name) values ('САРАТОВСКИЙ НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ Н.Г. ЧЕРНЫШЕВСКОГО', 'СГУ');
insert into "universities" (name, short_name) values ('САНКТ-ПЕТЕРБУРГСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНОЛОГИЧЕСКИЙ ИНСТИТУТ (ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ)', 'СПБГТИ(ТУ)');
insert into "universities" (name, short_name) values ('КАЗАНСКИЙ НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМ. А.Н. ТУПОЛЕВА-КАИ', 'КНИТУ-КАИ');
insert into "universities" (name, short_name) values ('САРАТОВСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ ГАГАРИНА Ю.А.', 'САРАТОВСКИЙ УНИВЕРСИТЕТ');
insert into "universities" (name, short_name) values ('УРАЛЬСКИЙ ГОСУДАРСТВЕННЫЙ ЮРИДИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ В.Ф. ЯКОВЛЕВА', 'УРГЮУ ИМЕНИ В.Ф. ЯКОВЛЕВА');
insert into "universities" (name, short_name) values ('ДОНЕЦКИЙ НАЦИОНАЛЬНЫЙ УНИВЕРСИТЕТ ЭКОНОМИКИ И ТОРГОВЛИ ИМЕНИ МИХАИЛА ТУГАН-БАРАНОВСКОГО', 'ДОННУЭТ');
insert into "universities" (name, short_name) values ('НОВОСИБИРСКИЙ ГОСУДАРСТВЕННЫЙ АРХИТЕКТУРНО-СТРОИТЕЛЬНЫЙ УНИВЕРСИТЕТ (СИБСТРИН)', 'НГАСУ (СИБСТРИН)');
insert into "universities" (name, short_name) values ('БЕЛГОРОДСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ ИМ. В.Г. ШУХОВА', 'БГТУ ИМ. В.Г. ШУХОВА');
insert into "universities" (name, short_name) values ('МАГНИТОГОРСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМ. Г.И. НОСОВА', 'МГТУ ИМ. Г. И. НОСОВА');
insert into "universities" (name, short_name) values ('УРАЛЬСКИЙ ГОСУДАРСТВЕННЫЙ АРХИТЕКТУРНО-ХУДОЖЕСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ Н.С. АЛФЁРОВА', 'УРГАХУ');
insert into "universities" (name, short_name) values ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ МОСКОВСКИЙ ГОСУДАРСТВЕННЫЙ СТРОИТЕЛЬНЫЙ УНИВЕРСИТЕТ', 'НИУ МГСУ');
insert into "universities" (name, short_name) values ('СЫКТЫВКАРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ ПИТИРИМА СОРОКИНА', 'СГУ ИМ. ПИТИРИМА СОРОКИНА');
insert into "universities" (name, short_name) values ('ЮЖНО-РОССИЙСКИЙ ГОСУДАРСТВЕННЫЙ ПОЛИТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ (НПИ) ИМЕНИ М.И. ПЛАТОВА', 'ЮРГПУ');
insert into "universities" (name, short_name) values ('САНКТ-ПЕТЕРБУРГСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ПРОМЫШЛЕННЫХ ТЕХНОЛОГИЙ И ДИЗАЙНА', 'СПБГУПТД');
insert into "universities" (name, short_name) values ('АРКТИЧЕСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИСКУССТВ, КУЛЬТУРЫ И КРЕАТИВНЫХ ИНДУСТРИЙ', 'АГУИККИ');
insert into "universities" (name, short_name) values ('САНКТ-ПЕТЕРБУРГСКИЙ ГОСУДАРСТВЕННЫЙ ЛЕСОТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ С.М. КИРОВА', 'СПБГЛТУ');
insert into "universities" (name, short_name) values ('СИБИРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИНЖЕНЕРИИ И БИОТЕХНОЛОГИЙ', 'УНИВЕРСИТЕТ БИОТЕХНОЛОГИЙ');
insert into "universities" (name, short_name) values ('МОСКОВСКИЙ ФИЗИКО-ТЕХНИЧЕСКИЙ ИНСТИТУТ (НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ)', 'МФТИ');
insert into "universities" (name, short_name) values ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ "МОСКОВСКИЙ ИНСТИТУТ ЭЛЕКТРОННОЙ ТЕХНИКИ', 'МИЭТ');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ ГОСУДАРСТВЕННЫЙ ГЕОЛОГОРАЗВЕДОЧНЫЙ УНИВЕРСИТЕТ ИМЕНИ СЕРГО ОРДЖОНИКИДЗЕ', 'МГРИ');
insert into "universities" (name, short_name) values ('САНКТ-ПЕТЕРБУРГСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ АЭРОКОСМИЧЕСКОГО ПРИБОРОСТРОЕНИЯ', 'ГУАП');
insert into "universities" (name, short_name) values ('КАЛУЖСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМ. К.Э. ЦИОЛКОВСКОГО', 'КГУ ИМ. К.Э. ЦИОЛКОВСКОГО');
insert into "universities" (name, short_name) values ('СЕВЕРО-ОСЕТИНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ КОСТА ЛЕВАНОВИЧА ХЕТАГУРОВА', 'СОГУ');
insert into "universities" (name, short_name) values ('ВЕРХНЕВОЛЖСКИЙ ГОСУДАРСТВЕННЫЙ АГРОБИОТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ', 'ВЕРХНЕВОЛЖСКИЙ ГАУ');
insert into "universities" (name, short_name) values ('КАМЧАТСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ ВИТУСА БЕРИНГА', 'КАМГУ ИМ. ВИТУСА БЕРИНГА');
insert into "universities" (name, short_name) values ('МОСКОВСКИЙ АВТОМОБИЛЬНО-ДОРОЖНЫЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ (МАДИ)', 'МАДИ');
insert into "universities" (name, short_name) values ('НИЖЕГОРОДСКИЙ ГОСУДАРСТВЕННЫЙ ЛИНГВИСТИЧЕСКИЙ УНИВЕРСИТЕТ ИМ. Н.А. ДОБРОЛЮБОВА', 'НГЛУ');
insert into "universities" (name, short_name) values ('УРАЛЬСКИЙ ФЕДЕРАЛЬНЫЙ УНИВЕРСИТЕТ ИМЕНИ ПЕРВОГО ПРЕЗИДЕНТА РОССИИ Б.Н. ЕЛЬЦИНА', 'УРФУ');
insert into "universities" (name, short_name) values ('МАРИУПОЛЬСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ А.И. КУИНДЖИ', 'МГУ ИМЕНИ А.И. КУИНДЖИ');
insert into "universities" (name, short_name) values ('ПРИАМУРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ ШОЛОМ-АЛЕЙХЕМА', 'ПГУ ИМ. ШОЛОМ-АЛЕЙХЕМА');
insert into "universities" (name, short_name) values ('БЕЛГОРОДСКИЙ ГОСУДАРСТВЕННЫЙ НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ', 'НИУ "БЕЛГУ');
insert into "universities" (name, short_name) values ('АСТРАХАНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ В.Н. ТАТИЩЕВА', 'АГУ ИМ. В.Н. ТАТИЩЕВА');
insert into "universities" (name, short_name) values ('ТАМБОВСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ Г.Р. ДЕРЖАВИНА', 'ТГУ ИМ. Г.Р. ДЕРЖАВИНА');
insert into "universities" (name, short_name) values ('САНКТ-ПЕТЕРБУРГСКИЙ ГОСУДАРСТВЕННЫЙ АРХИТЕКТУРНО-СТРОИТЕЛЬНЫЙ УНИВЕРСИТЕТ', 'СПБГАСУ');
insert into "universities" (name, short_name) values ('ВОРОНЕЖСКИЙ ГОСУДАРСТВЕННЫЙ ЛЕСОТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ Г.Ф. МОРОЗОВА', 'ВГЛТУ');
insert into "universities" (name, short_name) values ('ОРЛОВСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ И.С. ТУРГЕНЕВА', 'ОГУ ИМ. И.С. ТУРГЕНЕВА');
insert into "universities" (name, short_name) values ('МОСКОВСКИЙ АВИАЦИОННЫЙ ИНСТИТУТ (НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ)', 'МАИ');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ ЭКОНОМИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ Г.В. ПЛЕХАНОВА', 'РЭУ ИМ. Г.В. ПЛЕХАНОВА');
insert into "universities" (name, short_name) values ('РЯЗАНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ С.А. ЕСЕНИНА', 'РГУ ИМЕНИ С.А. ЕСЕНИНА');
insert into "universities" (name, short_name) values ('ЧУВАШСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ И.Н. УЛЬЯНОВА', 'ЧГУ ИМ. И.Н. УЛЬЯНОВА');
insert into "universities" (name, short_name) values ('ОРЛОВСКИЙ ГОСУДАРСТВЕННЫЙ АГРАРНЫЙ УНИВЕРСИТЕТ ИМЕНИ Н.В.ПАРАХИНА', 'ОРЛОВСКИЙ ГАУ');
insert into "universities" (name, short_name) values ('ТОМСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ СИСТЕМ УПРАВЛЕНИЯ И РАДИОЭЛЕКТРОНИКИ', 'ТУСУР');
insert into "universities" (name, short_name) values ('КУЗБАССКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ Т.Ф. ГОРБАЧЕВА', 'КУЗГТУ');
insert into "universities" (name, short_name) values ('РЯЗАНСКИЙ ГОСУДАРСТВЕННЫЙ РАДИОТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ В.Ф. УТКИНА', 'РГРТУ');
insert into "universities" (name, short_name) values ('ПРИМОРСКИЙ ГОСУДАРСТВЕННЫЙ АГРАРНО-ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ', 'ПРИМОРСКИЙ ГАТУ');
insert into "universities" (name, short_name) values ('ВОСТОЧНО-СИБИРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ТЕХНОЛОГИЙ И УПРАВЛЕНИЯ', 'ВСГУТУ');
insert into "universities" (name, short_name) values ('МОСКОВСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ "СТАНКИН', 'МГТУ "СТАНКИН');
insert into "universities" (name, short_name) values ('НИЖЕГОРОДСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМ. Р.Е. АЛЕКСЕЕВА', 'НГТУ');
insert into "universities" (name, short_name) values ('НОВОСИБИРСКИЙ НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'НГУ');
insert into "universities" (name, short_name) values ('ИВАНОВСКИЙ ГОСУДАРСТВЕННЫЙ ЭНЕРГЕТИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ В.И. ЛЕНИНА', 'ИГЭУ');
insert into "universities" (name, short_name) values ('НОВОСИБИРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ЭКОНОМИКИ И УПРАВЛЕНИЯ "НИНХ', 'НГУЭУ');
insert into "universities" (name, short_name) values ('САНКТ-ПЕТЕРБУРГСКИЙ ГОСУДАРСТВЕННЫЙ МОРСКОЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'СПБГМТУ');
insert into "universities" (name, short_name) values ('АЛТАЙСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ИМ. И.И. ПОЛЗУНОВА', 'АЛТГТУ');
insert into "universities" (name, short_name) values ('СИБИРСКИЙ ГОСУДАРСТВЕННЫЙ АВТОМОБИЛЬНО-ДОРОЖНЫЙ УНИВЕРСИТЕТ (СИБАДИ)', 'СИБАДИ');
insert into "universities" (name, short_name) values ('НИЖЕГОРОДСКИЙ ГОСУДАРСТВЕННЫЙ АРХИТЕКТУРНО-СТРОИТЕЛЬНЫЙ УНИВЕРСИТЕТ', 'ННГАСУ');
insert into "universities" (name, short_name) values ('КАЗАНСКИЙ НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ', 'КНИТУ');
insert into "universities" (name, short_name) values ('ЛУГАНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ ВЛАДИМИРА ДАЛЯ', 'ЛГУ ИМ. В. ДАЛЯ');
insert into "universities" (name, short_name) values ('ПЕРМСКИЙ НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ПОЛИТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ПНИПУ');
insert into "universities" (name, short_name) values ('КАБАРДИНО-БАЛКАРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМ. Х. М. БЕРБЕКОВА', 'КБГУ');
insert into "universities" (name, short_name) values ('БАЛТИЙСКИЙ ФЕДЕРАЛЬНЫЙ УНИВЕРСИТЕТ ИМЕНИ ИММАНУИЛА КАНТА', 'БФУ ИМ. И. КАНТА');
insert into "universities" (name, short_name) values ('СЕВЕРНЫЙ (АРКТИЧЕСКИЙ) ФЕДЕРАЛЬНЫЙ УНИВЕРСИТЕТ ИМЕНИ М.В. ЛОМОНОСОВА', 'САФУ');
insert into "universities" (name, short_name) values ('БРЯНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ АКАДЕМИКА И.Г. ПЕТРОВСКОГО', 'БГУ');
insert into "universities" (name, short_name) values ('ГОСУДАРСТВЕННЫЙ ИНСТИТУТ РУССКОГО ЯЗЫКА ИМ. А.С. ПУШКИНА', 'ИНСТИТУТ ПУШКИНА');
insert into "universities" (name, short_name) values ('ПЕНЗЕНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ АРХИТЕКТУРЫ И СТРОИТЕЛЬСТВА', 'ПГУАС');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ ХИМИКО-ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ ИМЕНИ Д.И. МЕНДЕЛЕЕВА', 'РХТУ');
insert into "universities" (name, short_name) values ('ИРКУТСКИЙ НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ИРНИТУ');
insert into "universities" (name, short_name) values ('КАРАЧАЕВО-ЧЕРКЕССКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ У.Д. АЛИЕВА', 'КЧГУ');
insert into "universities" (name, short_name) values ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ "МИСИС', 'МИСИС');
insert into "universities" (name, short_name) values ('ПЕРМСКИЙ ГОСУДАРСТВЕННЫЙ НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ', 'ПГУ');
insert into "universities" (name, short_name) values ('ЕЛЕЦКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМ. И.А. БУНИНА', 'ЕГУ ИМ. И.А. БУНИНА');
insert into "universities" (name, short_name) values ('РОСТОВСКИЙ ГОСУДАРСТВЕННЫЙ ЭКОНОМИЧЕСКИЙ УНИВЕРСИТЕТ (РИНХ)', 'РГЭУ (РИНХ)');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ СОЦИАЛЬНЫХ ТЕХНОЛОГИЙ', 'РГУ СОЦТЕХ');
insert into "universities" (name, short_name) values ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ТОМСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ТГУ');
insert into "universities" (name, short_name) values ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ТОМСКИЙ ПОЛИТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ТПУ');
insert into "universities" (name, short_name) values ('КАЗАНСКИЙ ГОСУДАРСТВЕННЫЙ АРХИТЕКТУРНО-СТРОИТЕЛЬНЫЙ УНИВЕРСИТЕТ', 'КГАСУ');
insert into "universities" (name, short_name) values ('МОСКОВСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ГЕОДЕЗИИ И КАРТОГРАФИИ', 'МИИГАИК');
insert into "universities" (name, short_name) values ('НОВГОРОДСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ ЯРОСЛАВА МУДРОГО', 'НОВГУ');
insert into "universities" (name, short_name) values ('САНКТ-ПЕТЕРБУРГСКИЙ ГОСУДАРСТВЕННЫЙ ЭКОНОМИЧЕСКИЙ УНИВЕРСИТЕТ', 'СПБГЭУ');
insert into "universities" (name, short_name) values ('САНКТ-ПЕТЕРБУРГСКИЙ ПОЛИТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ ПЕТРА ВЕЛИКОГО', 'СПБПУ');
insert into "universities" (name, short_name) values ('БРЯНСКИЙ ГОСУДАРСТВЕННЫЙ ИНЖЕНЕРНО-ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ', 'БГИТУ');
insert into "universities" (name, short_name) values ('КАЛМЫЦКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ Б.Б. ГОРОДОВИКОВА', 'КАЛМГУ');
insert into "universities" (name, short_name) values ('ВОЛГОГРАДСКИЙ ГОСУДАРСТВЕННЫЙ АГРАРНЫЙ УНИВЕРСИТЕТ', 'ВОЛГОГРАДСКИЙ ГАУ');
insert into "universities" (name, short_name) values ('ВОРОНЕЖСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИНЖЕНЕРНЫХ ТЕХНОЛОГИЙ', 'ВГУИТ');
insert into "universities" (name, short_name) values ('ИВАНОВСКИЙ ГОСУДАРСТВЕННЫЙ ХИМИКО-ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ', 'ИГХТУ');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ ГОСУДАРСТВЕННЫЙ ГИДРОМЕТЕОРОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ', 'РГГМУ');
insert into "universities" (name, short_name) values ('СИБИРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ГЕОСИСТЕМ И ТЕХНОЛОГИЙ', 'СГУГИТ');
insert into "universities" (name, short_name) values ('ТОМСКИЙ ГОСУДАРСТВЕННЫЙ АРХИТЕКТУРНО-СТРОИТЕЛЬНЫЙ УНИВЕРСИТЕТ', 'ТГАСУ');
insert into "universities" (name, short_name) values ('МОСКОВСКИЙ АРХИТЕКТУРНЫЙ ИНСТИТУТ (ГОСУДАРСТВЕННАЯ АКАДЕМИЯ)', 'МАРХИ');
insert into "universities" (name, short_name) values ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ЯДЕРНЫЙ УНИВЕРСИТЕТ "МИФИ', 'НИЯУ МИФИ');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ УНИВЕРСИТЕТ ТРАДИЦИОННЫХ ХУДОЖЕСТВЕННЫХ ПРОМЫСЛОВ', 'РУТХП');
insert into "universities" (name, short_name) values ('ПОВОЛЖСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ СЕРВИСА', 'УНИВЕРСИТЕТ СЕРВИСА');
insert into "universities" (name, short_name) values ('ГОСУДАРСТВЕННЫЙ АКАДЕМИЧЕСКИЙ УНИВЕРСИТЕТ ГУМАНИТАРНЫХ НАУК', 'ГАУГН');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ УНИВЕРСИТЕТ ДРУЖБЫ НАРОДОВ ИМЕНИ ПАТРИСА ЛУМУМБЫ', 'РУДН');
insert into "universities" (name, short_name) values ('ЗАПОЛЯРНЫЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМ. Н.М. ФЕДОРОВСКОГО', 'ЗГУ');
insert into "universities" (name, short_name) values ('ЯРОСЛАВСКИЙ ГОСУДАРСТВЕННЫЙ АГРАРНЫЙ УНИВЕРСИТЕТ', 'ЯРОСЛАВСКИЙ ГАУ');
insert into "universities" (name, short_name) values ('МИЧУРИНСКИЙ ГОСУДАРСТВЕННЫЙ АГРАРНЫЙ УНИВЕРСИТЕТ', 'МИЧУРИНСКИЙ ГАУ');
insert into "universities" (name, short_name) values ('ПОВОЛЖСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ', 'ВОЛГАТЕХ');
insert into "universities" (name, short_name) values ('БУРЯТСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМЕНИ ДОРЖИ БАНЗАРОВА', 'БГУ');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ТУРИЗМА И СЕРВИСА', 'РГУТИС');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ БИОТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ (РОСБИОТЕХ)', 'РОСБИОТЕХ');
insert into "universities" (name, short_name) values ('УФИМСКИЙ ГОСУДАРСТВЕННЫЙ НЕФТЯНОЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'УГНТУ');
insert into "universities" (name, short_name) values ('ПЕНЗЕНСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ', 'ПЕНЗГТУ');
insert into "universities" (name, short_name) values ('ЯРОСЛАВСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМ. П.Г. ДЕМИДОВА', 'ЯРГУ');
insert into "universities" (name, short_name) values ('ОМСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ ИМ. Ф.М. ДОСТОЕВСКОГО', 'ОМГУ');
insert into "universities" (name, short_name) values ('ВОЛГОГРАДСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ВОЛГГТУ');
insert into "universities" (name, short_name) values ('ИВАНОВСКИЙ ГОСУДАРСТВЕННЫЙ ПОЛИТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ИВГПУ');
insert into "universities" (name, short_name) values ('КУБАНСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ', 'КУБГТУ');
insert into "universities" (name, short_name) values ('РОССИЙСКО-ТАДЖИКСКИЙ (СЛАВЯНСКИЙ) УНИВЕРСИТЕТ', 'МОУ ВО РТСУ');
insert into "universities" (name, short_name) values ('МАЙКОПСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ', 'МГТУ');
insert into "universities" (name, short_name) values ('СИБИРСКИЙ ГОСУДАРСТВЕННЫЙ ИНДУСТРИАЛЬНЫЙ УНИВЕРСИТЕТ', 'СИБГИУ');
insert into "universities" (name, short_name) values ('УРАЛЬСКИЙ ГОСУДАРСТВЕННЫЙ ЛЕСОТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'УГЛТУ');
insert into "universities" (name, short_name) values ('МОСКОВСКИЙ ГОСУДАРСТВЕННЫЙ ЛИНГВИСТИЧЕСКИЙ УНИВЕРСИТЕТ', 'МГЛУ');
insert into "universities" (name, short_name) values ('НОВОСИБИРСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'НГТУ');
insert into "universities" (name, short_name) values ('УЛЬЯНОВСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'УЛГТУ');
insert into "universities" (name, short_name) values ('ДАГЕСТАНСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ДГТУ');
insert into "universities" (name, short_name) values ('ДОНБАССКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ДОНГТУ');
insert into "universities" (name, short_name) values ('КАЗАНСКИЙ ГОСУДАРСТВЕННЫЙ ЭНЕРГЕТИЧЕСКИЙ УНИВЕРСИТЕТ', 'КГЭУ');
insert into "universities" (name, short_name) values ('УРАЛЬСКИЙ ГОСУДАРСТВЕННЫЙ ЭКОНОМИЧЕСКИЙ УНИВЕРСИТЕТ', 'УРГЭУ');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ ГОСУДАРСТВЕННЫЙ ГУМАНИТАРНЫЙ УНИВЕРСИТЕТ', 'РГГУ');
insert into "universities" (name, short_name) values ('МИРЭА - РОССИЙСКИЙ ТЕХНОЛОГИЧЕСКИЙ УНИВЕРСИТЕТ', 'РТУ МИРЭА');
insert into "universities" (name, short_name) values ('САМАРСКИЙ ГОСУДАРСТВЕННЫЙ ЭКОНОМИЧЕСКИЙ УНИВЕРСИТЕТ', 'СГЭУ');
insert into "universities" (name, short_name) values ('ВОРОНЕЖСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ВГТУ');
insert into "universities" (name, short_name) values ('КОМСОМОЛЬСКИЙ-НА-АМУРЕ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'КНАГУ');
insert into "universities" (name, short_name) values ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ "МЭИ', 'НИУ "МЭИ');
insert into "universities" (name, short_name) values ('САМАРСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'САМГТУ');
insert into "universities" (name, short_name) values ('ЯРОСЛАВСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ЯГТУ');
insert into "universities" (name, short_name) values ('ТАМБОВСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ТГТУ');
insert into "universities" (name, short_name) values ('ТВЕРСКОЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ТВГТУ');
insert into "universities" (name, short_name) values ('РОССИЙСКИЙ ГОСУДАРСТВЕННЫЙ СОЦИАЛЬНЫЙ УНИВЕРСИТЕТ', 'РГСУ');
insert into "universities" (name, short_name) values ('УХТИНСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'УГТУ');
insert into "universities" (name, short_name) values ('ЛИПЕЦКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ЛГТУ');
insert into "universities" (name, short_name) values ('БРЯНСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'БГТУ');
insert into "universities" (name, short_name) values ('САРАТОВСКАЯ ГОСУДАРСТВЕННАЯ ЮРИДИЧЕСКАЯ АКАДЕМИЯ', 'СГЮА');
insert into "universities" (name, short_name) values ('ДОНСКОЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ДГТУ');
insert into "universities" (name, short_name) values ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ ИТМО', 'ИТМО');
insert into "universities" (name, short_name) values ('ОМСКИЙ ГОСУДАРСТВЕННЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ОМГТУ');
insert into "universities" (name, short_name) values ('ДОНЕЦКИЙ НАЦИОНАЛЬНЫЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ДОННТУ');
insert into "universities" (name, short_name) values ('КАЗАНСКИЙ (ПРИВОЛЖСКИЙ) ФЕДЕРАЛЬНЫЙ УНИВЕРСИТЕТ', 'КФУ');
insert into "universities" (name, short_name) values ('ПЕТРОЗАВОДСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ПЕТРГУ');
insert into "universities" (name, short_name) values ('СЕВЕРО-ВОСТОЧНЫЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'СВГУ');
insert into "universities" (name, short_name) values ('УРАЛЬСКИЙ ГОСУДАРСТВЕННЫЙ ГОРНЫЙ УНИВЕРСИТЕТ', 'УГГУ');
insert into "universities" (name, short_name) values ('ВЛАДИВОСТОКСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ВВГУ');
insert into "universities" (name, short_name) values ('МЕЛИТОПОЛЬСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'МЕЛГУ');
insert into "universities" (name, short_name) values ('НИЖНЕВАРТОВСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'НВГУ');
insert into "universities" (name, short_name) values ('ГОРНО-АЛТАЙСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ГАГУ');
insert into "universities" (name, short_name) values ('ВОЛГОГРАДСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ВОЛГУ');
insert into "universities" (name, short_name) values ('ЗАБАЙКАЛЬСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ЗАБГУ');
insert into "universities" (name, short_name) values ('СЕВЕРО-КАВКАЗСКАЯ ГОСУДАРСТВЕННАЯ АКАДЕМИЯ', 'СКГА');
insert into "universities" (name, short_name) values ('МОСКОВСКИЙ ПОЛИТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ПОЛИТЕХ');
insert into "universities" (name, short_name) values ('ТИХООКЕАНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ТОГУ');
insert into "universities" (name, short_name) values ('СЕВЕРО-КАВКАЗСКИЙ ФЕДЕРАЛЬНЫЙ УНИВЕРСИТЕТ', 'СКФУ');
insert into "universities" (name, short_name) values ('САХАЛИНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'САХГУ');
insert into "universities" (name, short_name) values ('СМОЛЕНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'СМОЛГУ');
insert into "universities" (name, short_name) values ('ПСКОВСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ПСКОВГУ');
insert into "universities" (name, short_name) values ('ТОЛЬЯТТИНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ТГУ');
insert into "universities" (name, short_name) values ('УФИМСКИЙ УНИВЕРСИТЕТ НАУКИ И ТЕХНОЛОГИЙ', 'УУНИТ');
insert into "universities" (name, short_name) values ('ЧЕЛЯБИНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ЧЕЛГУ');
insert into "universities" (name, short_name) values ('ЮГО-ЗАПАДНЫЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ЮЗГУ');
insert into "universities" (name, short_name) values ('ОРЕНБУРГСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ОГУ');
insert into "universities" (name, short_name) values ('УЛЬЯНОВСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'УЛГУ');
insert into "universities" (name, short_name) values ('ДАЛЬНЕВОСТОЧНЫЙ ФЕДЕРАЛЬНЫЙ УНИВЕРСИТЕТ', 'ДВФУ');
insert into "universities" (name, short_name) values ('ДАГЕСТАНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ДГУ');
insert into "universities" (name, short_name) values ('СОЧИНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'СОЧИГУ');
insert into "universities" (name, short_name) values ('ИВАНОВСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ИВГУ');
insert into "universities" (name, short_name) values ('КОСТРОМСКОЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'КГУ');
insert into "universities" (name, short_name) values ('ТУВИНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ТУВГУ');
insert into "universities" (name, short_name) values ('ТЮМЕНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ТЮМГУ');
insert into "universities" (name, short_name) values ('АЛТАЙСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'АЛТГУ');
insert into "universities" (name, short_name) values ('БАЙКАЛЬСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'БГУ');
insert into "universities" (name, short_name) values ('ВОРОНЕЖСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ВГУ');
insert into "universities" (name, short_name) values ('ПЯТИГОРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ПГУ');
insert into "universities" (name, short_name) values ('ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ УПРАВЛЕНИЯ', 'ГУУ');
insert into "universities" (name, short_name) values ('КУРГАНСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'КГУ');
insert into "universities" (name, short_name) values ('ТУЛЬСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ТУЛГУ');
insert into "universities" (name, short_name) values ('АДЫГЕЙСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'АГУ');
insert into "universities" (name, short_name) values ('ДОНЕЦКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ДОНГУ');
insert into "universities" (name, short_name) values ('АМУРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'АМГУ');
insert into "universities" (name, short_name) values ('БРАТСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'БРГУ');
insert into "universities" (name, short_name) values ('ВЯТСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ВЯТГУ');
insert into "universities" (name, short_name) values ('ГЖЕЛЬСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ГГУ');
insert into "universities" (name, short_name) values ('ИРКУТСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ИГУ');
insert into "universities" (name, short_name) values ('ТВЕРСКОЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ТВГУ');
insert into "universities" (name, short_name) values ('ЮГОРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'ЮГУ');
insert into "universities" (name, short_name) values ('КУРСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ', 'КГУ');
insert into "universities" (name, short_name) values ('МУРМАНСКИЙ АРКТИЧЕСКИЙ УНИВЕРСИТЕТ', 'МАУ');
insert into "universities" (name, short_name) values ('ХЕРСОНСКИЙ ТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ', 'ХТУ');
insert into "universities" (name, short_name) values ('СИБИРСКИЙ ФЕДЕРАЛЬНЫЙ УНИВЕРСИТЕТ', 'СФУ');
insert into "universities" (name, short_name) values ('ЮЖНЫЙ ФЕДЕРАЛЬНЫЙ УНИВЕРСИТЕТ', 'ЮФУ');

-- +goose Down
truncate table "universities";
