-- +goose Up
insert into "work_positions" (name) values ('Personnel Training and Development Manager');
insert into "work_positions" (name) values ('Information Security Specialist');
insert into "work_positions" (name) values ('Chief information officer (CIO)');
insert into "work_positions" (name) values ('Chief Technology Officer (CTO)');
insert into "work_positions" (name) values ('Software Performance Engineer');
insert into "work_positions" (name) values ('Chief Operating Officer (COO)');
insert into "work_positions" (name) values ('Chief Executive Officer (CEO)');
insert into "work_positions" (name) values ('Chief Financial Officer (CFO)');
insert into "work_positions" (name) values ('Mobile Application Developer');
insert into "work_positions" (name) values ('HR Brand Development Manager');
insert into "work_positions" (name) values ('Chief Product Officer (CPO)');
insert into "work_positions" (name) values ('Embedded Software Engineer');
insert into "work_positions" (name) values ('Quality Assurance Engineer');
insert into "work_positions" (name) values ('Quality Assurance Director');
insert into "work_positions" (name) values ('Quality Assurance Analyst');
insert into "work_positions" (name) values ('Quality Assurance Manager');
insert into "work_positions" (name) values ('Product Marketing Manager');
insert into "work_positions" (name) values ('System Software Engineer');
insert into "work_positions" (name) values ('Test Automation Engineer');
insert into "work_positions" (name) values ('Computer Graphics Artist');
insert into "work_positions" (name) values ('Computer Vision Engineer');
insert into "work_positions" (name) values ('Wireless System Engineer');
insert into "work_positions" (name) values ('Security Administrator');
insert into "work_positions" (name) values ('Database Administrator');
insert into "work_positions" (name) values ('Application Developer');
insert into "work_positions" (name) values ('System Administration');
insert into "work_positions" (name) values ('Manual Test Engineer');
insert into "work_positions" (name) values ('Application Designer');
insert into "work_positions" (name) values ('Designer Illustrator');
insert into "work_positions" (name) values ('Server Administrator');
insert into "work_positions" (name) values ('Data Center Engineer');
insert into "work_positions" (name) values ('Recruitment Director');
insert into "work_positions" (name) values ('Fullstack Developer');
insert into "work_positions" (name) values ('Recruitment Manager');
insert into "work_positions" (name) values ('Frontend Developer');
insert into "work_positions" (name) values ('Software Developer');
insert into "work_positions" (name) values ('Database Developer');
insert into "work_positions" (name) values ('Software Architect');
insert into "work_positions" (name) values ('Database Architect');
insert into "work_positions" (name) values ('Narrative Designer');
insert into "work_positions" (name) values ('Marketing Director');
insert into "work_positions" (name) values ('Site Administrator');
insert into "work_positions" (name) values ('Backend Developer');
insert into "work_positions" (name) values ('Hardware Engineer');
insert into "work_positions" (name) values ('Community manager');
insert into "work_positions" (name) values ('Security Engineer');
insert into "work_positions" (name) values ('Antifraud Analyst');
insert into "work_positions" (name) values ('Marketing Manager');
insert into "work_positions" (name) values ('Marketing Analyst');
insert into "work_positions" (name) values ('Business Analyst');
insert into "work_positions" (name) values ('Software Analyst');
insert into "work_positions" (name) values ('Product Designer');
insert into "work_positions" (name) values ('Graphic Designer');
insert into "work_positions" (name) values ('Project Director');
insert into "work_positions" (name) values ('Delivery Manager');
insert into "work_positions" (name) values ('Reverse Engineer');
insert into "work_positions" (name) values ('Network Engineer');
insert into "work_positions" (name) values ('Release Manager');
insert into "work_positions" (name) values ('Systems Analyst');
insert into "work_positions" (name) values ('Product Analyst');
insert into "work_positions" (name) values ('Motion Designer');
insert into "work_positions" (name) values ('Project Manager');
insert into "work_positions" (name) values ('Product Manager');
insert into "work_positions" (name) values ('Program Manager');
insert into "work_positions" (name) values ('AppSec-Engineer');
insert into "work_positions" (name) values ('Prompt Engineer');
insert into "work_positions" (name) values ('Game Developer');
insert into "work_positions" (name) values ('Mobile Analyst');
insert into "work_positions" (name) values ('UI/UX Designer');
insert into "work_positions" (name) values ('Flash Animator');
insert into "work_positions" (name) values ('Data Scientist');
insert into "work_positions" (name) values ('SEO Specialist');
insert into "work_positions" (name) values ('SMM Specialist');
insert into "work_positions" (name) values ('Web Developer');
insert into "work_positions" (name) values ('ERP Developer');
insert into "work_positions" (name) values ('Data Engineer');
insert into "work_positions" (name) values ('Game Designer');
insert into "work_positions" (name) values ('Targetologist');
insert into "work_positions" (name) values ('1C Developer');
insert into "work_positions" (name) values ('1C Architect');
insert into "work_positions" (name) values ('Data Analyst');
insert into "work_positions" (name) values ('Game Analyst');
insert into "work_positions" (name) values ('BI Developer');
insert into "work_positions" (name) values ('Web Designer');
insert into "work_positions" (name) values ('VUI-designer');
insert into "work_positions" (name) values ('Art Director');
insert into "work_positions" (name) values ('Scrum Master');
insert into "work_positions" (name) values ('NLP-Engineer');
insert into "work_positions" (name) values ('HTML Coding');
insert into "work_positions" (name) values ('Web Analyst');
insert into "work_positions" (name) values ('3d Animator');
insert into "work_positions" (name) values ('SOC Analyst');
insert into "work_positions" (name) values ('HR Director');
insert into "work_positions" (name) values ('ML Engineer');
insert into "work_positions" (name) values ('UX Analyst');
insert into "work_positions" (name) values ('1С Analyst');
insert into "work_positions" (name) values ('3d Modeler');
insert into "work_positions" (name) values ('PR-manager');
insert into "work_positions" (name) values ('HR Manager');
insert into "work_positions" (name) values ('Researcher');
insert into "work_positions" (name) values ('HR Analyst');
insert into "work_positions" (name) values ('UX Tester');
insert into "work_positions" (name) values ('Pentester');
insert into "work_positions" (name) values ('Sourcer');
insert into "work_positions" (name) values ('DevRel');
insert into "work_positions" (name) values ('DevOps');
insert into "work_positions" (name) values ('CCO');

-- +goose Down
truncate table "work_positions";
