@startuml database

entity "roles" <<prepared>> {
  * id : int <<PK>>
  --
  * name : varchar(31)
}

entity "statuses" <<prepared>> {
  * id : int <<PK>>
  --
  * name : varchar(127)
}

entity "social_types" <<prepared>> {
  * id : int <<PK>>
  --
  * name : varchar(31)
}

entity "edu_grade_types" <<prepared>> {
  * id : int <<PK>>
  --
  * name : varchar(31)
}

entity "key_skills" <<prepared>> {
  * id : int <<PK>>
  --
  * name : varchar(31)
}

entity "soft_skills" <<prepared>> {
  * id : int <<PK>>
  --
  * name : varchar(31)
}


entity "users" {
  * id : uuid <<PK>>
  --
  * photo_s3_id : varchar(255)
  * first_name : varchar(31)
  * last_name : varchar(31)
  * about_me : varchar(255)
  * status_id : int <<FK>>
  * role_id : int <<FK>>
}

entity "socials" {
  * id : int <<PK>>
  --
  * user_id : uuid <<FK>>
  * social_type_id : int <<FK>>
  * link : varchar(127)
  * is_preferred : bool
}

entity "work_places" {
  * id : int <<PK>>
  --
  * user_id : uuid <<FK>>
  * company_name : varchar(31)
  * grade : varchar(31)
  * position : varchar(31)
  * start_year : smallint
  end_year : smallint
  * is_working_now : bool
}

entity "edu_places" {
  * id : int <<PK>>
  --
  * user_id : uuid <<FK>>
  * edu_name : varchar(31)
  * grade_id : int <<FK>>
  level : varchar(31)
  * specialization : varchar(31)
  * start_year : smallint
  end_year : smallint
  * is_studying_now : bool
}

entity "faq" {
  * id : int <<PK>>
  --
  * question : varchar(255)
  * answer : varchar(255)
}

entity "announcements" {
  * id : uuid <<PK>>
  --
  * author_id : uuid <<FK>>
  * title : varchar(31)
  * content : varchar(255)
  * created_at : timestamptz
  * is_archived : bool
}

entity "news" {
  * id : uuid <<PK>>
  --
  * author_id : uuid <<FK>>
  * photo_s3_id : varchar(255)
  * title : varchar(31)
  * content : varchar(255)
  * created_at : timestamptz
}

entity "events" {
  * id : uuid <<PK>>
  --
  * author_id : uuid <<FK>>
  * photo_s3_id : varchar(255)
  * title : varchar(31)
  * content : varchar(255)
  * place : varchar(63)
  * starts_at : timestamptz
  registration_link : varchar(255)
  * created_at : timestamptz
}


entity "user_key_skills" {
  * user_id : uuid <<FK>>
  * key_skill_id : int <<FK>>
}

entity "user_soft_skills" {
  * user_id : uuid <<FK>>
  * soft_skill_id : int <<FK>>
}

entity "contact_notes" {
  * user_id : uuid <<FK>>
  * friend_id : uuid <<FK>>
  --
  * note : varchar(255)
}

entity "saved_users" {
  * user_id : uuid <<FK>>
  * saved_user_id : uuid <<FK>>
}

entity "announcement_responds" {
  * user_id : uuid <<FK>>
  * announcement_id : uuid <<FK>>
}

entity "event_responds" {
  * user_id : uuid <<FK>>
  * event_id : uuid <<FK>>
}


roles           ||--o{ users                : "role_id"
statuses        ||--o{ users                : "status_id"

users           ||--o{ socials              : "user_id"
social_types    ||--o{ socials              : "social_type_id"

users           ||--o{ work_places          : "user_id"

users           ||--o{ edu_places           : "user_id"
edu_grade_types ||--o{ edu_places           : "grade_id"

users           ||--o{ user_key_skills      : "user_id"
key_skills      ||--o{ user_key_skills      : "key_skill_id"

users           ||--o{ user_soft_skills     : "user_id"
soft_skills     ||--o{ user_soft_skills     : "soft_skill_id"

users           ||--o{ contact_notes        : "user_id"
users           ||--o{ contact_notes        : "friend_id"

users           ||--o{ saved_users          : "user_id"
users           ||--o{ saved_users          : "saved_user_id"

users           ||--o{ announcements        : "author_id"
announcements   ||--o{ announcement_responds : "announcement_id"
users           ||--o{ announcement_responds : "user_id"

users           ||--o{ news                 : "author_id"

users           ||--o{ events               : "author_id"
events          ||--o{ event_responds       : "event_id"
users           ||--o{ event_responds       : "user_id"

@enduml
